ln -s ~/DotFiles/.zshrc ~/.zshrc
ln -s ~/DotFiles/.zprofile ~/.zprofile
ln -s ~/DotFiles/.gemrc ~/.gemrc
ln -s ~/DotFiles/.bashrc ~/.bashrc
ln -s ~/DotFiles/.bash_profile ~/.bash_profile
ln -s ~/DotFiles/.gitconfig ~/.gitconfig
ln -s ~/DotFiles/.emacs ~/.emacs
ln -s ~/DotFiles/.emacs.d ~/.emacs.d
ln -s ~/DotFiles/.rspec ~/.rspec
